FROM python:3.11-slim

WORKDIR /app

COPY uv.txt .

RUN pip install --no-cache-dir uv && \
    uv pip install --no-cache-dir --system -r uv.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
