"""Pipeline orchestration service for the Data Forecaster backend.

Contains the :func:`run_pipeline` function that executes the full
6-agent forecasting pipeline.  Extracted from ``orchestrator.py`` to
separate concerns (pipeline, chat, RAG).
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

import pandas as pd

from agents.data_validation_agent import run_validation_agent
from agents.forecasting_agent import run_forecasting_agent
from agents.model_selection_agent import run_model_selection_agent
from agents.report_generation_agent import run_report_agent
from agents.statistical_analysis_agent import run_statistical_agent
from agents.statistical_review_agent import run_statistical_review_agent
from core.logging_config import get_logger
from exceptions import DataValidationError
from report.renderers import HTMLRenderer, MarkdownRenderer
from schemas import (
    AnalysisResponse,
    ForecastResult,
    ForecastCandidateResult,
    ModelSelectionResult,
    StatisticalResult,
    StatisticalReviewResult,
    ValidationResult,
)
from services.baseline_service import run_baseline_models
from services.rag_service import get_rag_kb
from utils.data_cleaning import apply_iqr_clipping, apply_zscore_clipping
from utils.preflight import prepare_series_frame
from utils.statistical import apply_boxcox, compute_acf_pacf, run_stl_decomposition
from utils.visualization import (
    chart_dict_to_png_b64,
    plot_acf_pacf,
    plot_forecast,
    plot_historical,
    plot_model_comparison,
    plot_stl,
)

logger = get_logger(__name__)


ProgressCallback = Callable[[int, str], None]


@dataclass(frozen=True)
class PreparedPipelineInput:
    """Normalized input data used by downstream pipeline stages."""

    frame: pd.DataFrame
    series: pd.Series
    freq: str
    seasonal_period: int
    disabled_statistical_tests: list[str]


@dataclass(frozen=True)
class StatisticalStageOutput:
    """Results produced by validation and statistical-analysis stages."""

    validation: ValidationResult
    statistical: StatisticalResult
    series: pd.Series


@dataclass(frozen=True)
class ForecastStageOutput:
    """Forecasting outputs, including review and model metrics."""

    model_selection: ModelSelectionResult
    forecast: ForecastResult
    statistical_review: StatisticalReviewResult
    all_metrics: dict[str, dict[str, float]]


@dataclass(frozen=True)
class ReportStageOutput:
    """Executive report content and metadata generated by the report stage."""

    executive_report: Any
    markdown: str
    html: str
    reasoning: list[dict[str, Any]]
    visual_strategy: list[dict[str, str]]
    token_usage: dict[str, Any]
    llm_fallback: bool


@dataclass(frozen=True)
class VisualizationStageOutput:
    """Interactive and PDF-ready charts generated for the analysis response."""

    historical: dict[str, Any]
    stl: dict[str, Any]
    acf_pacf: str
    forecast: dict[str, Any]
    model_comparison: dict[str, Any]
    historical_png: str
    stl_png: str
    forecast_png: str
    model_comparison_png: str


def run_pipeline(
    df: pd.DataFrame,
    file_id: str,
    date_col: str,
    value_col: str,
    freq: str,
    forecast_horizon: int,
    forced_model: str | None = None,
    user_prompt: str | None = None,
    preflight_options: dict[str, Any] | None = None,
    chroma_persist_dir: str = "./chroma_db",
    progress_callback: Callable[[int, str], None] | None = None,
) -> AnalysisResponse:
    """Execute the full 6-agent pipeline and return the complete AnalysisResponse.

    Args:
        df:                Input DataFrame.
        file_id:           Identifier for the uploaded file.
        date_col:          Name of the date column.
        value_col:         Name of the value column.
        freq:              Frequency string.
        forecast_horizon:  Number of future periods to forecast.
        forced_model:      Optional model override (``"ARIMA"``, ``"SARIMA"``,
                           ``"Holt-Winters"``).
        user_prompt:       Optional extra instructions for the report agent.
        preflight_options: Optional preflight configuration dict.
        chroma_persist_dir: Path to the ChromaDB persistence directory.
        progress_callback: Optional callback ``(pct, step)`` for progress updates.

    Returns:
        The complete :class:`AnalysisResponse`.
    """

    def _progress(pct: int, step: str) -> None:
        if progress_callback:
            progress_callback(pct, step)

    logger.info(
        "Pipeline start: file_id=%s date_col=%s value_col=%s freq=%s horizon=%d",
        file_id,
        date_col,
        value_col,
        freq,
        forecast_horizon,
    )

    if (preflight_options or {}).get("continue_short_series") == "stop":
        raise DataValidationError(
            "Analysis stopped because the selected series is too short."
        )

    prepared = _prepare_pipeline_input(df, date_col, value_col, freq, preflight_options)
    statistical_stage = _run_statistical_stages(
        prepared, date_col, value_col, preflight_options, _progress
    )
    forecast_stage = _run_forecast_stages(
        statistical_stage.series,
        statistical_stage.statistical,
        prepared.freq,
        prepared.seasonal_period,
        prepared.disabled_statistical_tests,
        forecast_horizon,
        forced_model,
        preflight_options,
        _progress,
    )
    report_stage = _run_report_stage(
        statistical_stage.validation,
        statistical_stage.statistical,
        forecast_stage,
        chroma_persist_dir,
        user_prompt,
        preflight_options,
        _progress,
    )
    visualization_stage = _build_visualizations(
        statistical_stage.series,
        statistical_stage.statistical,
        forecast_stage,
        prepared.seasonal_period,
        prepared.disabled_statistical_tests,
        _progress,
    )
    pipeline_token_usage = _build_pipeline_token_usage(
        statistical_stage, forecast_stage, report_stage.token_usage
    )

    logger.info("Pipeline complete: file_id=%s", file_id)
    _progress(100, "Analysis complete")

    return AnalysisResponse(
        file_id=file_id,
        validation=statistical_stage.validation,
        statistical=statistical_stage.statistical,
        model_selection=forecast_stage.model_selection,
        forecast=forecast_stage.forecast,
        statistical_review=forecast_stage.statistical_review,
        report=report_stage.markdown,
        executive_report=report_stage.executive_report.model_dump(),
        report_html=report_stage.html,
        report_reasoning=report_stage.reasoning,
        strategic_visual_recommendations=report_stage.visual_strategy,
        llm_fallback=report_stage.llm_fallback,
        chart_historical=visualization_stage.historical,
        chart_stl=visualization_stage.stl,
        chart_acf_pacf=visualization_stage.acf_pacf,
        chart_forecast=visualization_stage.forecast,
        chart_model_comparison=visualization_stage.model_comparison,
        chart_historical_png=visualization_stage.historical_png,
        chart_stl_png=visualization_stage.stl_png,
        chart_forecast_png=visualization_stage.forecast_png,
        chart_model_comparison_png=visualization_stage.model_comparison_png,
        pipeline_token_usage=pipeline_token_usage,
    )


def _prepare_pipeline_input(
    df: pd.DataFrame,
    date_col: str,
    value_col: str,
    freq: str,
    preflight_options: dict[str, Any] | None,
) -> PreparedPipelineInput:
    """Normalize data and derive statistical options for pipeline stages."""
    statistical_tuning = (preflight_options or {}).get("statistical_tuning") or {}
    disabled_statistical_tests = statistical_tuning.get("disabled_tests") or []
    if not isinstance(disabled_statistical_tests, list):
        disabled_statistical_tests = []

    prepared_df, prepared_freq = prepare_series_frame(
        df, date_col, value_col, preflight_options
    )
    series = prepared_df.set_index(date_col)[value_col].astype(float)
    seasonal_period = _freq_to_period(prepared_freq or freq)
    return PreparedPipelineInput(
        frame=prepared_df,
        series=series,
        freq=prepared_freq,
        seasonal_period=seasonal_period,
        disabled_statistical_tests=disabled_statistical_tests,
    )


def _run_statistical_stages(
    prepared: PreparedPipelineInput,
    date_col: str,
    value_col: str,
    preflight_options: dict[str, Any] | None,
    progress: ProgressCallback,
) -> StatisticalStageOutput:
    """Run validation, statistical analysis, and agent-selected remediation."""
    logger.info("Agent 1: Data Validation")
    progress(5, "Validating data…")
    validation_result = run_validation_agent(
        prepared.frame,
        date_col,
        value_col,
        prepared.freq,
        preflight_options=preflight_options,
    )
    progress(15, "Data validation complete")

    logger.info("Agent 2: Statistical Analysis")
    progress(20, "Running statistical analysis…")
    user_domain = (preflight_options or {}).get("data_domain", "Skip / Let AI Guess")
    stat_result = run_statistical_agent(
        prepared.series,
        prepared.seasonal_period,
        user_domain=user_domain,
        disabled_tests=prepared.disabled_statistical_tests,
    )
    progress(35, "Statistical analysis complete")

    series = _apply_agent_remediation(
        prepared.series,
        stat_result,
        prepared.disabled_statistical_tests,
        preflight_options,
    )
    return StatisticalStageOutput(
        validation=validation_result,
        statistical=stat_result,
        series=series,
    )


def _apply_agent_remediation(
    series: pd.Series,
    stat_result: StatisticalResult,
    disabled_statistical_tests: list[str],
    preflight_options: dict[str, Any] | None,
) -> pd.Series:
    """Apply safe, agent-recommended transformations before forecasting."""
    remediated = series
    if (preflight_options or {}).get("outlier_strategy") == "Let AI Decide":
        if "iqr_clip" in stat_result.recommended_remediation:
            logger.info("Agent decided to APPLY IQR clipping.")
            remediated = apply_iqr_clipping(remediated)
            logger.info("IQR clipping applied successfully.")
        elif "zscore_clip" in stat_result.recommended_remediation:
            logger.info("Agent decided to APPLY Z-score clipping.")
            remediated = apply_zscore_clipping(remediated)
            logger.info("Z-score clipping applied successfully.")
        else:
            logger.info(
                "Agent decided to SKIP outlier clipping "
                "(likely determined outliers are signal)."
            )

    if (
        "box_cox" in stat_result.recommended_remediation
        and "box_cox" not in disabled_statistical_tests
    ):
        logger.info("Agent decided to APPLY Box-Cox transformation.")
        try:
            remediated, _ = apply_boxcox(remediated)
            stat_result.summary += (
                "\n\n(Note: A Box-Cox transformation was applied to stabilize "
                "variance based on agent recommendation.)"
            )
        except (TypeError, ValueError) as exc:
            logger.warning("Box-Cox application failed: %s", exc)

    if (
        "change_point_analysis" in stat_result.recommended_remediation
        and "change_points" not in disabled_statistical_tests
    ):
        logger.info(
            "Agent detected significant change points. Adding note to analysis."
        )
        stat_result.summary += (
            "\n\n(Note: Change point analysis detected structural breaks. "
            "Consider segmenting the data for improved forecasting accuracy.)"
        )
    return remediated


def _run_forecast_stages(
    series: pd.Series,
    stat_result: StatisticalResult,
    freq: str,
    seasonal_period: int,
    disabled_statistical_tests: list[str],
    forecast_horizon: int,
    forced_model: str | None,
    preflight_options: dict[str, Any] | None,
    progress: ProgressCallback,
) -> ForecastStageOutput:
    """Run model selection, forecasting, baselines, review, and optional retry."""
    model_selection = _select_model(stat_result, forced_model, progress)

    logger.info("Agent 4: Forecasting")
    progress(60, "Running forecast…")
    forecast_result, all_metrics = run_forecasting_agent(
        series,
        model_selection,
        stat_result,
        forecast_horizon,
        freq,
        disabled_tests=disabled_statistical_tests,
        loss_preference=(preflight_options or {}).get("loss_metric", "mase"),
        preprocessing_options=preflight_options,
    )
    if model_selection.selection_method != "forced":
        model_selection = model_selection.model_copy(
            update={
                "selected_model": forecast_result.model_used,
                "selection_method": "deterministic",
                "explanation": (
                    "Selected from common rolling-origin out-of-sample evidence. "
                    "LLM narrative did not control the numerical ranking."
                ),
                "selection_evidence": {
                    "metric_source": "rolling_origin_backtest",
                    "validation_design": forecast_result.validation_design,
                    "all_metrics": all_metrics,
                    "forecast_context": {
                        key: (preflight_options or {}).get(key)
                        for key in (
                            "units",
                            "loss_metric",
                            "interventions",
                            "censoring_or_stockouts",
                            "known_future_covariates",
                            "aggregation",
                            "minimum_value",
                            "maximum_value",
                        )
                        if (preflight_options or {}).get(key) is not None
                    },
                },
            }
        )
    progress(75, "Forecast complete")

    logger.info("Running baseline model comparisons")
    baseline_results = run_baseline_models(series, forecast_horizon, seasonal_period)
    for name, result in baseline_results.items():
        all_metrics.setdefault(
            name,
            {
                "RMSE": result.metrics.rmse,
                "MAE": result.metrics.mae,
                "MAPE": result.metrics.mape,
                "WAPE": result.metrics.wape,
                "MASE": result.metrics.mase,
            },
        )
    forecast_result = forecast_result.model_copy(
        update={
            "candidate_results": [
                *forecast_result.candidate_results,
                *[
                    ForecastCandidateResult(
                        model=name,
                        status=result.status,
                        failure_reason=result.failure_reason,
                        is_fallback=result.is_fallback,
                        rmse=all_metrics[name].get("RMSE"),
                        mae=all_metrics[name].get("MAE"),
                        mape=all_metrics[name].get("MAPE"),
                        wape=all_metrics[name].get("WAPE"),
                        mase=all_metrics[name].get("MASE"),
                        n_evaluated=result.metrics.n_evaluated,
                        n_missing=result.metrics.n_missing,
                        fitted_configuration=result.fitted_configuration,
                        warnings=result.warnings,
                        interval_label=result.interval_label,
                    )
                    for name, result in baseline_results.items()
                    if name
                    not in {item.model for item in forecast_result.candidate_results}
                ],
            ]
        }
    )
    logger.info("Baseline models complete")

    statistical_review = _run_statistical_review(
        stat_result, model_selection, forecast_result, all_metrics, progress
    )

    return _maybe_retry_forecast_after_review(
        series,
        stat_result,
        model_selection,
        forecast_result,
        statistical_review,
        all_metrics,
        forecast_horizon,
        freq,
        disabled_statistical_tests,
        forced_model,
        preflight_options,
        progress,
    )


def _select_model(
    stat_result: StatisticalResult,
    forced_model: str | None,
    progress: ProgressCallback,
) -> ModelSelectionResult:
    """Select a forecasting model or create the forced-model contract."""
    if forced_model:
        logger.info(
            "Agent 3: Model Selection skipped — user forced model: %s", forced_model
        )
        progress(40, f"Model manually set to {forced_model}")
        model_selection = ModelSelectionResult(
            selected_model=forced_model,
            explanation=f"Model manually selected by user: {forced_model}.",
            selection_method="forced",
            narrative_claims=[
                {
                    "claim": f"User forced selection of {forced_model}.",
                    "evidence_references": ["request.forced_model"],
                    "uncertainty": "user_directed",
                }
            ],
            holt_winters_rejected_reason=(
                None
                if forced_model == "Holt-Winters"
                else "Not selected (user chose a different model)."
            ),
            arima_rejected_reason=(
                None
                if forced_model == "ARIMA"
                else "Not selected (user chose a different model)."
            ),
            sarima_rejected_reason=(
                None
                if forced_model == "SARIMA"
                else "Not selected (user chose a different model)."
            ),
            reasoning_steps=[
                {
                    "thought": (
                        f"User explicitly requested the {forced_model} model. "
                        "Skipping automated model selection logic."
                    ),
                    "observation": f"Manual selection active: {forced_model}",
                }
            ],
        )
    else:
        logger.info("Agent 3: Model Selection")
        progress(40, "Selecting forecasting model…")
        model_selection = run_model_selection_agent(stat_result)
    progress(55, f"Model selected: {model_selection.selected_model}")
    return model_selection


def _run_statistical_review(
    stat_result: StatisticalResult,
    model_selection: ModelSelectionResult,
    forecast_result: ForecastResult,
    all_metrics: dict[str, dict[str, float]],
    progress: ProgressCallback,
) -> StatisticalReviewResult:
    """Run the statistical QA review stage."""
    logger.info("Agent 4.5: Statistical Review")
    progress(77, "Statistical review…")
    statistical_review = run_statistical_review_agent(
        stat_result, model_selection, forecast_result, all_metrics
    )
    progress(80, "Statistical review complete")
    return statistical_review


def _maybe_retry_forecast_after_review(
    series: pd.Series,
    stat_result: StatisticalResult,
    model_selection: ModelSelectionResult,
    forecast_result: ForecastResult,
    statistical_review: StatisticalReviewResult,
    all_metrics: dict[str, dict[str, float]],
    forecast_horizon: int,
    freq: str,
    disabled_statistical_tests: list[str],
    forced_model: str | None,
    preflight_options: dict[str, Any] | None,
    progress: ProgressCallback,
) -> ForecastStageOutput:
    """Retry forecasting once when statistical review identifies critical issues."""
    retry_enabled = (preflight_options or {}).get(
        "statistical_review_retry_enabled", True
    )
    has_critical = any(
        flag.get("severity") == "critical" for flag in statistical_review.flags
    )
    if not (retry_enabled and (has_critical or statistical_review.verdict == "fail")):
        return ForecastStageOutput(
            model_selection=model_selection,
            forecast=forecast_result,
            statistical_review=statistical_review,
            all_metrics=all_metrics,
        )

    # Respect the deterministic selection policy. The review agent can only
    # override a deterministic selection when it has a typed, code-recognized
    # reason (can_override_selection=True).
    if (
        model_selection.selection_method == "deterministic"
        and not statistical_review.can_override_selection
    ):
        logger.info(
            "Statistical review flagged issues but cannot override the "
            "deterministic selection (no typed override reason). Skipping retry."
        )
        return ForecastStageOutput(
            model_selection=model_selection,
            forecast=forecast_result,
            statistical_review=statistical_review,
            all_metrics=all_metrics,
        )

    logger.info(
        "Statistical review flagged critical issues — re-running model "
        "selection with review feedback."
    )
    progress(82, "Re-running model selection with review feedback…")

    prev_model_selection_usage = dict(model_selection.token_usage)
    prev_forecast_usage = dict(forecast_result.token_usage)
    prev_review_usage = dict(statistical_review.token_usage)
    review_feedback = statistical_review.summary

    if forced_model:
        logger.info(
            "Forced model '%s' — skipping model reselection, appending review "
            "feedback only.",
            forced_model,
        )
        model_selection = model_selection.model_copy(
            update={
                "explanation": (
                    f"{model_selection.explanation}\n\n"
                    f"[Statistical Review Feedback]: {review_feedback}"
                )
            }
        )
    else:
        previous_model = model_selection.selected_model
        model_selection = run_model_selection_agent(
            stat_result,
            review_feedback=review_feedback,
            exclude_model=previous_model,
            all_metrics=all_metrics,
        )
        model_selection = model_selection.model_copy(
            update={
                "explanation": (
                    f"{model_selection.explanation}\n\n"
                    f"[Statistical Review Feedback]: {review_feedback}"
                )
            }
        )

    progress(85, "Re-running forecast with revised model…")
    forecast_result, all_metrics = run_forecasting_agent(
        series,
        model_selection,
        stat_result,
        forecast_horizon,
        freq,
        existing_metrics=all_metrics,
        disabled_tests=disabled_statistical_tests,
        loss_preference=(preflight_options or {}).get("loss_metric", "mase"),
        preprocessing_options=preflight_options,
    )
    progress(87, "Re-running statistical review…")
    statistical_review = run_statistical_review_agent(
        stat_result, model_selection, forecast_result, all_metrics
    )
    progress(88, "Statistical review re-run complete")

    return ForecastStageOutput(
        model_selection=model_selection.model_copy(
            update={
                "token_usage": _merge_token_usage(
                    prev_model_selection_usage, model_selection.token_usage
                )
            }
        ),
        forecast=forecast_result.model_copy(
            update={
                "token_usage": _merge_token_usage(
                    prev_forecast_usage, forecast_result.token_usage
                )
            }
        ),
        statistical_review=statistical_review.model_copy(
            update={
                "token_usage": _merge_token_usage(
                    prev_review_usage, statistical_review.token_usage
                )
            }
        ),
        all_metrics=all_metrics,
    )


def _run_report_stage(
    validation_result: ValidationResult,
    stat_result: StatisticalResult,
    forecast_stage: ForecastStageOutput,
    chroma_persist_dir: str,
    user_prompt: str | None,
    preflight_options: dict[str, Any] | None,
    progress: ProgressCallback,
) -> ReportStageOutput:
    """Generate and render the executive report."""
    logger.info("Agent 5: Report Generation")
    progress(90, "Generating report…")
    rag_kb = get_rag_kb(chroma_persist_dir)
    executive_report, report_reasoning, visual_strategy, report_token_usage = (
        run_report_agent(
            validation_result,
            stat_result,
            forecast_stage.model_selection,
            forecast_stage.forecast,
            rag_kb,
            user_prompt=user_prompt,
            preflight_options=preflight_options,
            statistical_review=forecast_stage.statistical_review,
            all_metrics=forecast_stage.all_metrics,
        )
    )
    report_md, report_html = _render_report_outputs(executive_report)
    progress(92, "Report complete")
    return ReportStageOutput(
        executive_report=executive_report,
        markdown=report_md,
        html=report_html,
        reasoning=report_reasoning,
        visual_strategy=visual_strategy,
        token_usage=report_token_usage,
        llm_fallback=any(step.get("llm_fallback", False) for step in report_reasoning),
    )


def _render_report_outputs(executive_report: Any) -> tuple[str, str]:
    """Render Markdown and HTML report variants with best-effort fallback."""
    try:
        md_renderer = MarkdownRenderer()
        html_renderer = HTMLRenderer()
        return md_renderer.render(executive_report), html_renderer.render(
            executive_report
        )
    except (AttributeError, KeyError, TypeError, ValueError) as exc:
        logger.warning("Report rendering failed: %s — using empty render output.", exc)
        return "", ""


def _build_visualizations(
    series: pd.Series,
    stat_result: StatisticalResult,
    forecast_stage: ForecastStageOutput,
    seasonal_period: int,
    disabled_statistical_tests: list[str],
    progress: ProgressCallback,
) -> VisualizationStageOutput:
    """Build interactive charts and PDF chart images for analysis results."""
    logger.info("Generating visualizations")
    progress(95, "Generating visualizations…")
    chart_historical = plot_historical(series)
    chart_stl = _build_stl_chart(
        series,
        stat_result.seasonal_period or seasonal_period,
        disabled_statistical_tests,
    )
    chart_acf_pacf = _build_acf_pacf_chart(series, disabled_statistical_tests)
    chart_forecast = plot_forecast(series, forecast_stage.forecast)
    chart_model_comparison = plot_model_comparison(forecast_stage.all_metrics)

    return VisualizationStageOutput(
        historical=chart_historical,
        stl=chart_stl,
        acf_pacf=chart_acf_pacf,
        forecast=chart_forecast,
        model_comparison=chart_model_comparison,
        historical_png=_chart_to_png(chart_historical, "Historical"),
        stl_png=_chart_to_png(chart_stl, "STL"),
        forecast_png=_chart_to_png(chart_forecast, "Forecast"),
        model_comparison_png=_chart_to_png(chart_model_comparison, "Model comparison"),
    )


def _build_stl_chart(
    series: pd.Series,
    seasonal_period: int,
    disabled_statistical_tests: list[str],
) -> dict[str, Any]:
    """Build the STL chart when the test is enabled."""
    try:
        if "stl" in disabled_statistical_tests:
            return {}
        stl_data = run_stl_decomposition(series, period=seasonal_period)
        return plot_stl(series, stl_data, seasonal_period)
    except (KeyError, TypeError, ValueError, RuntimeError) as exc:
        logger.warning("STL chart failed: %s", exc)
        return {}


def _build_acf_pacf_chart(
    series: pd.Series,
    disabled_statistical_tests: list[str],
) -> str:
    """Build the ACF/PACF chart when the test is enabled."""
    try:
        if "acf_pacf" in disabled_statistical_tests:
            return ""
        acf_data = compute_acf_pacf(series)
        return plot_acf_pacf(
            acf_data["acf_values"], acf_data["pacf_values"], acf_data["lags"]
        )
    except (KeyError, TypeError, ValueError, RuntimeError) as exc:
        logger.warning("ACF/PACF chart failed: %s", exc)
        return ""


def _chart_to_png(chart: dict[str, Any], label: str) -> str:
    """Convert a chart dictionary to base64 PNG with best-effort fallback."""
    try:
        return chart_dict_to_png_b64(chart)
    except (KeyError, TypeError, ValueError, RuntimeError, OSError) as exc:
        logger.warning("%s chart PNG failed: %s", label, exc)
        return ""


def _build_pipeline_token_usage(
    statistical_stage: StatisticalStageOutput,
    forecast_stage: ForecastStageOutput,
    report_token_usage: dict[str, Any],
) -> dict[str, Any]:
    """Aggregate token usage from all pipeline stages."""
    agent_usage = {
        "validation": statistical_stage.validation.token_usage,
        "statistical": statistical_stage.statistical.token_usage,
        "model_selection": forecast_stage.model_selection.token_usage,
        "forecast": forecast_stage.forecast.token_usage,
        "statistical_review": forecast_stage.statistical_review.token_usage,
        "report": report_token_usage,
    }
    grand_total = {
        "input_tokens": sum(u.get("input_tokens", 0) for u in agent_usage.values()),
        "output_tokens": sum(u.get("output_tokens", 0) for u in agent_usage.values()),
        "total_tokens": sum(u.get("total_tokens", 0) for u in agent_usage.values()),
    }
    estimated = any(u.get("estimated", False) for u in agent_usage.values())
    pipeline_token_usage = {
        "agents": agent_usage,
        "grand_total": grand_total,
        "estimated": estimated,
    }
    logger.info(
        "Pipeline token usage: input=%d output=%d total=%d (estimated=%s)",
        grand_total["input_tokens"],
        grand_total["output_tokens"],
        grand_total["total_tokens"],
        estimated,
    )
    return pipeline_token_usage


def _merge_token_usage(
    first: dict[str, int | bool],
    second: dict[str, int | bool],
) -> dict[str, int | bool]:
    """Merge two token-usage dicts by summing their numeric values.

    Args:
        first:  Token usage from the first attempt.
        second: Token usage from the retry attempt.

    Returns:
        A new dict with summed values for ``input_tokens``,
        ``output_tokens``, and ``total_tokens``.  The ``estimated`` flag is
        set to ``True`` if either input was estimated.
    """
    merged: dict[str, int | bool] = {}
    for key in ("input_tokens", "output_tokens", "total_tokens"):
        merged[key] = int(first.get(key, 0)) + int(second.get(key, 0))
    merged["estimated"] = first.get("estimated", False) or second.get(
        "estimated", False
    )
    return merged


def _freq_to_period(freq: str) -> int:
    """Convert a frequency string to a seasonal period integer.

    Args:
        freq: Pandas frequency string (e.g. ``"MS"``, ``"Q"``, ``"D"``).

    Returns:
        The number of periods in one seasonal cycle (default 12).
    """
    f = (freq or "").upper().lstrip("-")
    if f.startswith("MS") or f.startswith("M"):
        return 12
    if f.startswith("QS") or f.startswith("Q"):
        return 4
    if f.startswith("W"):
        return 52
    if f.startswith("D"):
        return 7
    if f.startswith("H"):
        return 24
    if f.startswith("Y") or f.startswith("A"):
        return 1
    return 12
