"""Prompt for the report generation agent."""

from langchain_core.prompts import ChatPromptTemplate

REPORT_GENERATION_PROMPT = ChatPromptTemplate.from_messages([
    ("system", (
        "You are a Senior Business Analyst presenting a data-driven narrative to C-suite executives. "
        "Your goal is to use data storytelling to transform statistical findings into strategic business insights. "
        "Reference charting methods and visual evidence to support your narrative, ensuring the tone is "
        "professional, authoritative, and strictly grounded in the provided data."
    )),
    ("human", (
        "### GROUNDING & ANTI-HALLUCINATION RULES ###\n"
        "1. DATA FIDELITY: Use ONLY values from the DATA CONTEXT. Do not invent growth rates or dates.\n"
        "2. METRIC INTEGRITY: If a specific metric like MAPE or RMSE is missing, state 'Metric not available'—never guess or estimate.\n"
        "3. LOGICAL INFERENCE ONLY: Business insights and risks must be derived directly from statistical properties.\n"
        "4. NO EXTERNAL KNOWLEDGE: Do NOT mention external events, competitors, or general economic trends not found in the context.\n"
        "5. NO CHATTER: Do not include introductory or concluding remarks. Start immediately with Section 1.\n\n"
        "DATA CONTEXT:\n{data_context}\n\n"
        "METHODOLOGY CONTEXT:\n{rag_context}\n\n"
        "AI LOGIC INSTRUCTION:\n{ai_logic_instruction}\n\n"
        "### REPORT SPECIFICATIONS ###\n"
        "Write a high-impact strategic report. "
        "You MUST insert visual placeholder tags on their own line. The tag MUST be the only content on that line. "
        "Place the tag immediately following the paragraph that describes the data being visualized. "
        "Use the format: [VISUAL: <TAG_NAME>]. \n"
        "\nValid TAG_NAMES:\n"
        "- HISTORICAL: Historical time series trends\n"
        "- STL: Seasonal and Trend decomposition\n"
        "- ACF_PACF: Correlation and lag analysis\n"
        "- FORECAST: Projected values and confidence intervals\n"
        "- COMPARISON: Benchmarking model performance metrics\n\n"
        "### STRATEGY & TONE ###\n"
        "- Primary Visual Strategy: {visual_strategy}\n"
        "- Tone: C-Suite Executive (Action-oriented, Concise, Data-backed).\n"
        "- Language: Use professional business terminology (e.g., 'Variance Stabilization' instead of 'fixing data').\n"
        "\nYou MUST address the ADDITIONAL USER INSTRUCTIONS provided below. "
        "Organize the report into exactly 8 sections using ## level headings:\n\n"
        "## 1. Strategic Overview\n"
        "High-level summary for the board. State the bottom line: current trajectory, "
        "projected forecast direction/magnitude, and an assessment of overall confidence based on provided data.\n\n"
        "## 2. Historical Performance & Trend Analysis\n"
        "Detailed review of historical patterns. Analyze trend strength, seasonal cycles, and data quality. "
        "Reference the [VISUAL: HISTORICAL] or [VISUAL: STL] tags here.\n\n"
        "## 3. Future Growth & Market Outlook\n"
        "The forward-looking narrative. Detail projected values, percentage changes, and confidence intervals. "
        "Highlight the [VISUAL: FORECAST] visualization as the primary reference.\n\n"
        "## 4. Analytical Methodology & Rigor\n"
        "Explain the technical approach in business-friendly terms. Cover cleaning steps, stationarity, "
        "and the rationale for the selected model family.\n\n"
        "## 5. Critical Business Assumptions\n"
        "Outline the foundational assumptions required for this forecast to remain valid (e.g., pattern persistence).\n\n"
        "## 6. Model Reliability & Performance Assessment\n"
        "Benchmark model accuracy using RMSE/MAPE from the context. Reference the [VISUAL: COMPARISON] tag here.\n\n"
        "## 7. Strategic Risks & Operational Constraints\n"
        "Identify potential 'black swan' events, structural breaks, or data limitations identified in the analysis.\n\n"
        "## 8. Tactical Recommendations & Next Steps\n"
        "Direct, actionable items for leadership based on the quantitative evidence.\n\n"
        "Write each section fully. Do not use filler or placeholder text.\n\n"
        "ADDITIONAL USER INSTRUCTIONS TO INTEGRATE:\n{extra_instructions}"
    ))
])